cloudinary_products:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/products") %>

cloudinary_product_categories:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/product_categories") %>

cloudinary_slides:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/slides") %>

cloudinary_banners:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/banners") %>

cloudinary_reparation_categories:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/reparation_categories") %>
