// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import '@hotwired/turbo-rails'
import 'controllers'
import 'popper'
import 'bootstrap'

import 'components/add_to_cart'
import 'components/checkout_form'
import 'components/flash'
import 'components/navbar'
import 'components/preview_image_on_file_select'
import 'components/price_range_slider'
import 'components/product_show_thumbnails'
import 'components/product_show_variants'
import 'components/products_filters_form'
import 'components/products_search'
import 'components/products_sidebar'
import 'components/products_sorting'
import 'components/quantity_selector'